language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install -U pip
install:
  - pip install codecov
  - pip install -r requirements_full.txt
  - pip install -e .[test]
script: 
  - coverage run --source=earthdata_download -m py.test -v
after_success: 
  - codecov
